name: Update IP List

on:
  # 定时触发：每3小时运行一次
  schedule:
    - cron: '0 */3 * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        else
          pip install requests beautifulsoup4
        fi
      env:
        PYTHONUSERBASE: ${{ github.workspace }}/.local
      shell: bash

    - name: Run IP collection script
      run: |
        if [ -f "${{ github.workspace }}/collect_ips.py" ]; then
          python "${{ github.workspace }}/collect_ips.py"
        else
          echo "Error: collect_ips.py not found!"
          exit 1
        fi
      env:
        LOG_LEVEL: INFO

    - name: Commit and push changes
      run: |
        # 安全设置默认值（确保字符串闭合且无语法错误）
        EMAIL=${{ secrets.GIT_EMAIL || 'your-email@example.com' }}
        NAME=${{ secrets.GIT_NAME || 'Your Name' }}
    
        git config --global user.email "$EMAIL"
        git config --global user.name "$NAME"
        CHANGED_FILES=$(git status --porcelain ip.txt)
        if [ -n "$CHANGED_FILES" ]; then
          echo "Detected changes in ip.txt"
          git add ip.txt
          git commit -m "Automatic update: $(date +'%Y-%m-%d %H:%M:%S')"
          if ! git push; then
            echo "Push failed, trying again..."
            git push || echo "Second push failed, giving up."
          fi
        else
          echo "No changes in ip.txt, skipping commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
